'use client'
import Link from 'next/link'
import { Filter, Search, X } from 'lucide-react'
import { useState } from 'react'

export type AdmissionSearchParams = { q?: string; institution?: string; level?: string; type?: string; deadline?: string; verified?: string }

export default function AdmissionFilters({ searchParams, count }: { searchParams: AdmissionSearchParams; count: number }) {
  const [mobileOpen, setMobileOpen] = useState(false)
  const active = Object.values(searchParams).some(Boolean)
  const field = 'h-11 w-full rounded-xl border border-gray-200 bg-white px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/10'
  return <aside className="rounded-2xl border border-gray-200 bg-white p-5 lg:sticky lg:top-24"><div className="flex items-center justify-between lg:mb-5"><h2 className="flex items-center gap-2 text-sm font-bold text-ink"><Filter className="h-4 w-4 text-primary" />Filter admissions</h2><div className="flex items-center gap-3">{active && <Link href="/admissions" className="flex items-center gap-1 text-xs font-semibold text-red-500"><X className="h-3 w-3" />Clear</Link>}<button type="button" onClick={() => setMobileOpen(value => !value)} className="rounded-lg border border-gray-200 px-3 py-1.5 text-xs font-bold text-primary lg:hidden">{mobileOpen ? 'Hide filters' : 'Filters'}</button></div></div><form action="/admissions" className={`mt-5 space-y-4 ${mobileOpen ? 'block' : 'hidden'} lg:mt-0 lg:block`}>
    <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-500">Search</span><span className="relative block"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" /><input name="q" defaultValue={searchParams.q} placeholder="Institution or program…" className={`${field} pl-9`} /></span></label>
    <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-500">Institution</span><select name="institution" defaultValue={searchParams.institution || ''} className={field}><option value="">All institutions</option><option value="school">Schools</option><option value="college">Colleges</option><option value="university">Universities</option><option value="training_provider">Training providers</option></select></label>
    <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-500">Education level</span><select name="level" defaultValue={searchParams.level || ''} className={field}><option value="">All levels</option><optgroup label="Schools (up to Grade 10)"><option value="ECD / Grade 1-10">ECD / Grade 1–10</option><option value="SEE">SEE</option></optgroup><optgroup label="Colleges (post-SEE)"><option value="+2">+2</option><option value="Diploma">Diploma</option><option value="Certificate">Certificate</option><option value="Bachelor">Bachelor</option><option value="Master">Master</option><option value="MPhil">MPhil</option><option value="PhD">PhD</option></optgroup></select></label>
    <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-500">Admission type</span><select name="type" defaultValue={searchParams.type || ''} className={field}><option value="">All types</option><option value="general">General admission</option><option value="entrance">Entrance based</option><option value="scholarship">Scholarship</option><option value="quota">Quota</option><option value="transfer">Transfer</option></select></label>
    <label className="block"><span className="mb-1.5 block text-xs font-semibold text-gray-500">Deadline</span><select name="deadline" defaultValue={searchParams.deadline || ''} className={field}><option value="">Any deadline</option><option value="7">Next 7 days</option><option value="30">Next 30 days</option><option value="open">Open opportunities</option></select></label>
    <label className="flex items-center gap-2 rounded-xl border border-gray-200 px-3 py-2.5 text-sm text-gray-600"><input type="checkbox" name="verified" value="true" defaultChecked={searchParams.verified === 'true'} className="accent-primary" />Verified only</label>
    <button className="w-full rounded-xl bg-primary px-4 py-3 text-sm font-bold text-white">Show {count} result{count === 1 ? '' : 's'}</button>
  </form></aside>
}
