import type { Metadata } from 'next'
import Link from 'next/link'
import { ArrowRight, BriefcaseBusiness, SearchCheck } from 'lucide-react'
import { careers } from '@/lib/careers'

export const metadata: Metadata = { title: 'Career Explorer', description: 'Explore practical education and career routes in Nepal, with official sources to check before deciding.' }

export default function CareersPage() {
  const categories = Array.from(new Set(careers.map((career) => career.category)))
  return <main className="min-h-screen bg-[#f8f7f3]"><section className="border-b border-[#e6e4df] bg-[#16233f] text-white"><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-blue-200"><span className="h-px w-7 bg-[#c93b37]" />Career explorer</p><h1 className="mt-4 max-w-3xl font-display text-4xl font-bold leading-tight sm:text-5xl">A clearer route from what you enjoy to what you can build.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-blue-100">Straightforward guides for Nepal: study routes, likely entry requirements, skills to practise and the official sources you should verify.</p></div></section><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><div className="mb-7 flex flex-wrap gap-2">{categories.map((category) => <a key={category} href={`#${category.toLowerCase().replaceAll(' ', '-')}`} className="rounded-full border border-[#d9d6cf] bg-white px-3 py-1.5 text-xs font-bold text-slate-700 hover:border-primary hover:text-primary">{category}</a>)}</div>{categories.map((category) => <section id={category.toLowerCase().replaceAll(' ', '-')} key={category} className="mb-12"><div className="mb-4 flex items-center gap-2"><BriefcaseBusiness className="h-5 w-5 text-[#c93b37]" /><h2 className="font-display text-2xl font-bold">{category}</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{careers.filter((career) => career.category === category).map((career) => <Link key={career.slug} href={`/careers/${career.slug}`} className="group rounded-xl border border-[#e6e4df] bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-primary hover:shadow-md"><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#9a302c]">{career.category}</p><h3 className="mt-2 font-display text-xl font-bold text-ink">{career.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{career.summary}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-primary">Explore route <ArrowRight className="h-4 w-4 transition group-hover:translate-x-0.5" /></span></Link>)}</div></section>)}</div><section className="border-t border-[#e6e4df] bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-4 py-9 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex gap-3"><SearchCheck className="mt-1 h-5 w-5 shrink-0 text-primary" /><p className="max-w-2xl text-sm leading-6 text-slate-600"><strong className="text-ink">Use this as a starting point, not a promise.</strong> Entry rules, licensing and job opportunities change. Check the official source on every guide before you invest time or money.</p></div><Link href="/my-path" className="shrink-0 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white">Add this to My Path</Link></div></section></main>
}
