import type { Metadata } from 'next'
import Link from 'next/link'
import { Award, Calendar, CheckCircle2, ExternalLink, Search } from 'lucide-react'
import { createServerSupabaseClient } from '@/lib/supabase'
import type { Scholarship } from '@/types'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'Scholarship Finder Nepal – Check Funding Options', description: 'Match scholarships in Nepal by study level, funding type and student eligibility, with official sources and verified deadlines.' }
const LEVELS = ['+2', 'Bachelor', 'Master', 'Diploma']
const GROUPS: Record<string,string> = { merit: 'Merit-based', need_based: 'Financial need', female: 'Female students', disability: 'Students with disabilities', dalit: 'Dalit students', janajati: 'Janajati students', remote_area: 'Remote-area students' }
const date = (value: string) => new Date(value).toLocaleDateString('en-NP', { day: 'numeric', month: 'short', year: 'numeric' })

export default async function ScholarshipsPage({ searchParams }: { searchParams: { q?: string; level?: string; group?: string; open?: string } }) {
  const db = createServerSupabaseClient()
  let query = db.from('scholarships').select('*, college:colleges(name,slug,location)').eq('is_active', true).order('deadline', { ascending: true, nullsFirst: false }).limit(100)
  if (searchParams.q) query = query.or(`title.ilike.%${searchParams.q}%,provider_name.ilike.%${searchParams.q}%,eligibility.ilike.%${searchParams.q}%`)
  if (searchParams.level) query = query.contains('education_levels', [searchParams.level])
  if (searchParams.group) query = query.contains('target_groups', [searchParams.group])
  if (searchParams.open === 'true') query = query.gte('deadline', new Date().toISOString())
  const { data } = await query
  const items = (data || []) as Scholarship[]
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a302c]">Funding that fits you</p><h1 className="mt-2 font-display text-4xl font-bold text-ink">Scholarship finder</h1><p className="mt-3 leading-7 text-slate-600">Filter by your study level and situation. A match means “worth checking”—final eligibility always comes from the official provider.</p></div>
    <form className="mt-7 grid gap-3 rounded-xl border border-gray-200 bg-white p-4 shadow-sm md:grid-cols-4"><label className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-gray-400"/><input name="q" defaultValue={searchParams.q} placeholder="Search scholarships" className="w-full rounded-lg border border-gray-200 py-3 pl-9 pr-3 text-sm"/></label><select name="level" defaultValue={searchParams.level||''} className="rounded-lg border border-gray-200 bg-white px-3 text-sm"><option value="">Any study level</option>{LEVELS.map(x=><option key={x}>{x}</option>)}</select><select name="group" defaultValue={searchParams.group||''} className="rounded-lg border border-gray-200 bg-white px-3 text-sm"><option value="">Any eligibility group</option>{Object.entries(GROUPS).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><button className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-white">Show my matches</button><label className="flex items-center gap-2 text-sm text-slate-600 md:col-span-4"><input type="checkbox" name="open" value="true" defaultChecked={searchParams.open==='true'}/>Only show future deadlines</label></form>
    <div className="mt-8 flex items-end justify-between"><div><h2 className="text-xl font-bold text-ink">Matching opportunities</h2><p className="mt-1 text-sm text-slate-500">{items.length} result{items.length===1?'':'s'}</p></div><Link href="/scholarships" className="text-sm font-bold text-primary">Clear filters</Link></div>
    {items.length?<div className="mt-4 grid gap-5 md:grid-cols-2">{items.map(s=><article key={s.id} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">{s.scholarship_type||'Scholarship'}</p><h3 className="mt-1 text-lg font-bold text-ink">{s.title}</h3><p className="mt-1 text-sm text-slate-500">{s.provider_name||s.college?.name||'Scholarship provider'}</p></div><Award className="h-6 w-6 shrink-0 text-amber-500"/></div>{s.coverage&&<p className="mt-4 rounded-lg bg-emerald-50 px-3 py-2 text-sm font-semibold text-emerald-800">{s.coverage}</p>}<div className="mt-4 flex flex-wrap gap-2">{(s.education_levels||[]).map(x=><span key={x} className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{x}</span>)}{(s.target_groups||[]).slice(0,3).map(x=><span key={x} className="rounded-full bg-gray-100 px-2.5 py-1 text-xs text-gray-600">{GROUPS[x]||x}</span>)}</div>{s.eligibility&&<p className="mt-4 line-clamp-3 text-sm leading-6 text-slate-600"><strong className="text-ink">Who can apply:</strong> {s.eligibility}</p>}<div className="mt-5 flex flex-wrap items-center gap-4 border-t border-gray-100 pt-4 text-xs">{s.deadline&&<span className="flex items-center gap-1 font-bold text-orange-700"><Calendar className="h-3.5 w-3.5"/>Deadline {date(s.deadline)}</span>}{s.last_verified_at&&<span className="flex items-center gap-1 text-slate-500"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-600"/>Checked {date(s.last_verified_at)}</span>}<a href={s.application_url||s.source_url||'#'} target="_blank" rel="noopener noreferrer" className="ml-auto flex items-center gap-1 font-bold text-primary">Official details <ExternalLink className="h-3.5 w-3.5"/></a></div></article>)}</div>:<div className="mt-4 rounded-xl border border-gray-200 bg-white py-16 text-center"><Award className="mx-auto h-10 w-10 text-gray-300"/><h3 className="mt-3 font-bold text-ink">No matching scholarships</h3><p className="mt-1 text-sm text-slate-500">Clear a filter or check again when new verified opportunities are added.</p></div>}
  </div>
}
