import type { Metadata } from 'next'
import Link from 'next/link'
import { Calendar, ExternalLink, Search, ShieldCheck, Sparkles } from 'lucide-react'
import { createServerSupabaseClient } from '@/lib/supabase'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'Internships & Student Opportunities Nepal', description: 'Find verified internships, fellowships, competitions, courses and volunteering opportunities for students in Nepal.' }
type Opportunity = { id:string; title:string; opportunity_type:string; organisation:string; location:string|null; eligibility:string|null; summary:string; application_url:string; source_url:string|null; deadline:string|null; is_verified:boolean; last_verified_at:string|null }
const TYPES:Record<string,string>={internship:'Internships',apprenticeship:'Apprenticeships',fellowship:'Fellowships',competition:'Competitions',course:'Short courses',volunteering:'Volunteering',project:'Project challenges'}
const date=(value:string|null)=>value?new Intl.DateTimeFormat('en-NP',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value)):'Rolling / see source'

export default async function OpportunitiesPage({searchParams}:{searchParams:{q?:string;type?:string;deadline?:string}}){
  const db=createServerSupabaseClient()
  let query=db.from('student_opportunities').select('id,title,opportunity_type,organisation,location,eligibility,summary,application_url,source_url,deadline,is_verified,last_verified_at').eq('is_published',true).order('deadline',{ascending:true,nullsFirst:false}).limit(100)
  if(searchParams.q)query=query.or(`title.ilike.%${searchParams.q}%,organisation.ilike.%${searchParams.q}%,summary.ilike.%${searchParams.q}%`)
  if(searchParams.type)query=query.eq('opportunity_type',searchParams.type)
  if(searchParams.deadline==='open')query=query.or(`deadline.is.null,deadline.gte.${new Date().toISOString()}`)
  const {data}=await query
  const items=(data||[]) as Opportunity[]
  return <main className="min-h-screen bg-[#f8f7f3]"><section className="border-b border-[#e6e4df] bg-[#16233f] text-white"><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><p className="text-xs font-bold uppercase tracking-[.14em] text-blue-200">Build experience while you study</p><h1 className="mt-3 max-w-3xl font-display text-4xl font-bold sm:text-5xl">Opportunities for Nepal&apos;s students</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-blue-100">Internships, fellowships, competitions, projects, volunteering and practical short courses—with direct links to the organiser.</p></div></section><div className="mx-auto max-w-6xl px-4 py-9 sm:px-6">
    <form className="-mt-14 mb-7 grid gap-3 rounded-xl border border-[#e6e4df] bg-white p-4 shadow-md md:grid-cols-[1fr_220px_auto]"><label className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400"/><input name="q" defaultValue={searchParams.q} placeholder="Search role, skill or organisation" className="w-full rounded-lg border border-slate-200 py-3 pl-9 pr-3 text-sm"/></label><select name="type" defaultValue={searchParams.type||''} className="rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="">All opportunity types</option>{Object.entries(TYPES).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button className="rounded-lg bg-primary px-5 py-3 text-sm font-bold text-white">Find opportunities</button><label className="flex items-center gap-2 text-sm text-slate-600 md:col-span-3"><input type="checkbox" name="deadline" value="open" defaultChecked={searchParams.deadline==='open'}/>Hide opportunities whose deadline has passed</label></form>
    <div className="mb-7 flex gap-3 rounded-xl border border-[#e6e4df] bg-white p-4 text-sm leading-6 text-slate-700"><ShieldCheck className="h-5 w-5 shrink-0 text-primary"/><p><strong>Apply safely:</strong> use the official link, confirm the deadline and never pay an unofficial person for selection. “Verified” means we checked the source—not that SikshyaNepal guarantees acceptance.</p></div><div className="mb-4 flex items-end justify-between"><div><h2 className="font-display text-2xl font-bold text-ink">Current listings</h2><p className="mt-1 text-sm text-slate-500">{items.length} matching opportunit{items.length===1?'y':'ies'}</p></div><Link href="/opportunities" className="text-sm font-bold text-primary">Clear filters</Link></div>
    {items.length?<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(item=>{const expired=Boolean(item.deadline&&new Date(item.deadline)<new Date());return <article key={item.id} className="flex flex-col rounded-xl border border-[#e6e4df] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#9a302c]">{TYPES[item.opportunity_type]||item.opportunity_type}</p>{item.is_verified&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-emerald-700">SOURCE CHECKED</span>}</div><h2 className="mt-2 font-display text-xl font-bold text-ink">{item.title}</h2><p className="mt-1 text-sm font-semibold text-primary">{item.organisation}{item.location?` · ${item.location}`:''}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{item.summary}</p>{item.eligibility&&<p className="mt-3 text-xs leading-5 text-slate-500"><strong>Who can apply:</strong> {item.eligibility}</p>}<div className="mt-auto pt-5"><div className={`flex items-center gap-1 border-t border-[#e6e4df] pt-3 text-xs font-semibold ${expired?'text-red-700':'text-slate-600'}`}><Calendar className="h-3.5 w-3.5"/>{expired?'Deadline passed: ':'Deadline: '}{date(item.deadline)}</div><div className="mt-4 flex items-center justify-between"><a href={item.source_url||item.application_url} target="_blank" rel="noreferrer" className="text-xs font-semibold text-slate-500 hover:text-primary">Check source</a><a href={item.application_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-sm font-bold text-primary hover:underline">Apply officially <ExternalLink className="h-4 w-4"/></a></div></div></article>})}</div>:<section className="rounded-xl border border-dashed border-[#cfcac1] bg-white p-10 text-center"><Sparkles className="mx-auto h-8 w-8 text-primary"/><h2 className="mt-4 font-display text-2xl font-bold">No verified matches yet</h2><p className="mx-auto mt-2 max-w-xl text-sm leading-6 text-slate-600">Clear a filter or check back as new official opportunities are reviewed.</p></section>}
  </div></main>
}
