'use client'
import { useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowRight, Compass, RotateCcw, Sparkles } from 'lucide-react'

const questions = [
  { key: 'interest', title: 'What interests you most?', options: [['technology', 'Building apps and solving digital problems'], ['business', 'Business, money, and leading projects'], ['science', 'Science, health, and understanding how things work'], ['people', 'Helping people and improving communities'], ['creative', 'Writing, ideas, communication, and society']] },
  { key: 'style', title: 'What type of work sounds most enjoyable?', options: [['practical', 'Practical projects and hands-on work'], ['analysis', 'Analysis, research, and problem-solving'], ['people', 'Working directly with people'], ['creative', 'Creating, presenting, and communicating']] },
  { key: 'strength', title: 'Which school subject feels strongest?', options: [['math', 'Mathematics / computer studies'], ['science', 'Science / biology'], ['commerce', 'Account / economics'], ['language', 'Languages / social studies']] },
]
const labels: Record<string, { faculty: string; title: string; description: string }> = { IT: { faculty: 'IT', title: 'IT & Computing', description: 'Explore BCA, BIT, BSc CSIT, software, and computing-focused programs.' }, Management: { faculty: 'Management', title: 'Management & Business', description: 'Explore BBA, BBS, BBM, accounting, finance, and entrepreneurship pathways.' }, Medical: { faculty: 'Medical', title: 'Medical & Health Sciences', description: 'Explore health-science pathways and confirm subject and entrance requirements carefully.' }, Engineering: { faculty: 'Engineering', title: 'Engineering & Technical Studies', description: 'Explore engineering and technical programs with a strong mathematics and science base.' }, Nursing: { faculty: 'Nursing', title: 'Nursing & People-focused Care', description: 'Explore nursing, education, and care-oriented study paths.' }, Humanities: { faculty: 'Humanities', title: 'Humanities, Law & Social Sciences', description: 'Explore law, media, humanities, education, and social-science programs.' } }
function recommendation(answers: Record<string, string>) { if (answers.interest === 'technology' || answers.strength === 'math') return labels.IT; if (answers.interest === 'business' || answers.strength === 'commerce') return labels.Management; if (answers.interest === 'science' && answers.style === 'practical') return labels.Medical; if (answers.interest === 'science' || answers.strength === 'science') return labels.Engineering; if (answers.interest === 'people' || answers.style === 'people') return labels.Nursing; return labels.Humanities }

export default function ProgramFinderPage() { const [answers, setAnswers] = useState<Record<string, string>>({}); const done = questions.every(question => answers[question.key]); const result = useMemo(() => done ? recommendation(answers) : null, [answers, done]); const choose = (key: string, value: string) => setAnswers(all => ({ ...all, [key]: value })); return <div className="min-h-screen bg-[#f0f4ff]"><section className="border-b border-gray-200 bg-white"><div className="mx-auto max-w-3xl px-4 py-12 sm:px-6"><p className="text-xs font-bold uppercase tracking-widest text-primary">Student tools</p><h1 className="mt-3 font-display text-3xl font-extrabold text-ink sm:text-4xl">What should I study?</h1><p className="mt-3 text-gray-500">Answer three quick questions for a study-area suggestion, then explore real colleges and official program requirements.</p></div></section><main className="mx-auto max-w-3xl px-4 py-8 sm:px-6"><div className="rounded-2xl border border-gray-200 bg-white p-5 sm:p-8">{questions.map((question, index) => <section key={question.key} className={index ? 'mt-8 border-t border-gray-100 pt-8' : ''}><p className="text-xs font-bold uppercase tracking-widest text-primary">Question {index + 1} of {questions.length}</p><h2 className="mt-2 font-display text-xl font-bold text-ink">{question.title}</h2><div className="mt-4 grid gap-2">{question.options.map(([value, label]) => <button key={value} onClick={() => choose(question.key, value)} className={`rounded-xl border p-4 text-left text-sm font-semibold transition-colors ${answers[question.key] === value ? 'border-primary bg-blue-50 text-primary' : 'border-gray-200 text-gray-600 hover:border-blue-300'}`}>{label}</button>)}</div></section>)}<button onClick={() => setAnswers({})} className="mt-8 inline-flex items-center gap-1.5 text-sm font-semibold text-gray-500 hover:text-primary"><RotateCcw className="h-4 w-4" />Start again</button></div>{result && <section className="mt-6 rounded-2xl bg-[#0d1b3e] p-6 text-white"><Sparkles className="h-6 w-6 text-blue-300" /><p className="mt-4 text-sm font-semibold text-blue-200">A study area to explore</p><h2 className="mt-1 font-display text-2xl font-bold">{result.title}</h2><p className="mt-3 leading-7 text-blue-100/80">{result.description}</p><Link href={`/colleges?level=bachelor&faculty=${encodeURIComponent(result.faculty)}`} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-bold text-primary hover:bg-blue-50"><Compass className="h-4 w-4" />Explore matching colleges <ArrowRight className="h-4 w-4" /></Link><p className="mt-5 text-xs leading-5 text-blue-100/60">This is a starting point based on your answers, not a career assessment or eligibility decision. Confirm subjects, GPA requirements, fees, entrance rules, and official notices.</p></section>}</main></div> }
