'use client'

import { useState } from 'react'
import Link from 'next/link'
import { DatabaseZap, ShieldAlert } from 'lucide-react'

export default function EvidenceBootstrapPage(){
  const [running,setRunning]=useState(false),[result,setResult]=useState<{created:number;colleges_scanned?:number;message?:string}|null>(null),[error,setError]=useState('')
  async function run(){if(!window.confirm('Create pending evidence candidates from sourced fields in the first 50 active college profiles? Nothing will be publicly verified.'))return;setRunning(true);setError('');setResult(null);const response=await fetch('/api/admin/evidence/bootstrap',{method:'POST'}),data=await response.json();setRunning(false);if(!response.ok)return setError(data.error||'Bootstrap failed.');setResult(data)}
  return <div className="p-5 text-gray-100 sm:p-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-widest text-cyan-400">Controlled import</p><h1 className="mt-2 flex items-center gap-2 text-2xl font-bold"><DatabaseZap className="h-6 w-6"/>Bootstrap college evidence</h1><p className="mt-3 text-sm leading-6 text-gray-400">Convert existing sourced profile fields into reviewable evidence candidates. This scans up to 50 active colleges and creates candidates only for affiliation, programmes and contact details.</p><div className="mt-6 rounded-xl border border-amber-800 bg-amber-950/30 p-5"><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0 text-amber-300"/><div><h2 className="font-bold text-amber-200">Nothing is automatically trusted</h2><p className="mt-1 text-sm leading-6 text-amber-100/80">Every imported claim starts as pending with 60% extraction confidence. An editor must open the source and verify the exact claim before it appears publicly. Existing matching evidence is skipped.</p></div></div></div>{error&&<p role="alert" className="mt-5 rounded-lg border border-red-800 bg-red-950/40 p-4 text-red-300">{error}</p>}{result&&<div className="mt-5 rounded-xl border border-emerald-800 bg-emerald-950/30 p-5 text-emerald-200"><strong>{result.created} pending evidence candidates created.</strong><p className="mt-1 text-sm">{result.message||`${result.colleges_scanned} college profiles scanned.`}</p></div>}<div className="mt-6 flex flex-wrap gap-3"><button onClick={()=>void run()} disabled={running} className="min-h-11 rounded-lg bg-blue-600 px-5 text-sm font-bold disabled:opacity-50">{running?'Scanning safely…':'Create pending candidates'}</button><Link href="/admin/evidence" className="min-h-11 rounded-lg border border-gray-600 px-5 py-3 text-sm font-bold text-gray-200">Review Evidence Ledger</Link><Link href="/admin/evidence-coverage" className="min-h-11 rounded-lg border border-gray-600 px-5 py-3 text-sm font-bold text-gray-200">View coverage audit</Link></div></div></div>
}
