'use client'

import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, Clock3, ExternalLink, Flag } from 'lucide-react'

type Correction = { id:string; entity_type:'school'|'college'; entity_id:string; entity_name:string; correction_type:string; details:string; source_url:string|null; reporter_name:string|null; reporter_email:string; reporter_role:string|null; status:string; resolution_notes:string|null; reviewed_at:string|null; created_at:string }
type View = 'attention'|'reviewing'|'resolved'|'all'
const resolvedStatuses=['accepted','rejected']
const urgentTypes=['incorrect_information','closed_or_moved','program_update']

function timing(item:Correction){
  const ageHours=Math.max(0,Math.floor((Date.now()-new Date(item.created_at).getTime())/3_600_000))
  const targetHours=urgentTypes.includes(item.correction_type)?24:72
  const remaining=targetHours-ageHours
  return { ageHours,targetHours,overdue:remaining<0,label:remaining<0?`${Math.abs(remaining)}h overdue`:remaining===0?'Due now':`${remaining}h left` }
}

export default function CorrectionsPage(){
  const [items,setItems]=useState<Correction[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[view,setView]=useState<View>('attention'),[busy,setBusy]=useState<string|null>(null)
  useEffect(()=>{fetch('/api/admin/corrections',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[])
  async function change(item:Correction,status:string){setBusy(item.id);setError('');const notes=resolvedStatuses.includes(status)?window.prompt('Add a short resolution note (recommended):',item.resolution_notes||'')||'':null;const r=await fetch(`/api/admin/corrections/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,resolution_notes:notes})});if(!r.ok){setBusy(null);return setError('Update failed.')}const updated=await r.json();setItems(all=>all.map(x=>x.id===updated.id?updated:x));setBusy(null)}
  const counts=useMemo(()=>({attention:items.filter(i=>i.status==='pending').length,reviewing:items.filter(i=>i.status==='reviewing').length,resolved:items.filter(i=>resolvedStatuses.includes(i.status)).length,overdue:items.filter(i=>!resolvedStatuses.includes(i.status)&&timing(i).overdue).length}),[items])
  const shown=useMemo(()=>items.filter(i=>view==='all'||(view==='attention'?i.status==='pending':view==='reviewing'?i.status==='reviewing':resolvedStatuses.includes(i.status))).sort((a,b)=>{const ao=!resolvedStatuses.includes(a.status)&&timing(a).overdue,bo=!resolvedStatuses.includes(b.status)&&timing(b).overdue;return Number(bo)-Number(ao)||new Date(a.created_at).getTime()-new Date(b.created_at).getTime()}),[items,view])

  return <div className="p-5 text-gray-100 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Flag className="h-6 w-6 text-orange-400"/>Data corrections</h1><p className="mt-1 max-w-2xl text-sm text-gray-400">Verify every report against a reliable source. Urgent factual reports target 24 hours; other reports target 72 hours.</p></div><p className="rounded-lg border border-gray-700 bg-gray-800 px-3 py-2 text-xs text-gray-400">SLA starts when submitted</p></div>
    {error&&<p role="alert" className="mt-5 rounded-lg bg-red-950/50 p-3 text-red-300">{error}</p>}
    {!loading&&<><section className="mt-7 grid gap-3 sm:grid-cols-4" aria-label="Correction queue summary">{[{label:'Needs attention',value:counts.attention,tone:'text-amber-300'},{label:'In review',value:counts.reviewing,tone:'text-blue-300'},{label:'Overdue',value:counts.overdue,tone:'text-red-300'},{label:'Resolved',value:counts.resolved,tone:'text-emerald-300'}].map(card=><div key={card.label} className="rounded-xl border border-gray-700 bg-gray-800 p-4"><p className="text-xs font-bold uppercase tracking-wide text-gray-500">{card.label}</p><p className={`mt-2 text-2xl font-bold ${card.tone}`}>{card.value}</p></div>)}</section>
      <div className="mt-6 flex gap-2 overflow-x-auto pb-1" role="group" aria-label="Filter correction reports">{(['attention','reviewing','resolved','all'] as View[]).map(option=><button key={option} onClick={()=>setView(option)} aria-pressed={view===option} className={`min-h-11 whitespace-nowrap rounded-lg px-4 text-sm font-bold capitalize ${view===option?'bg-blue-600 text-white':'border border-gray-700 bg-gray-800 text-gray-300 hover:border-gray-500'}`}>{option}</button>)}</div>
      <div className="mt-5 grid gap-4 xl:grid-cols-2">{shown.map(item=>{const time=timing(item),resolved=resolvedStatuses.includes(item.status);return <article key={item.id} className={`rounded-xl border bg-gray-800 p-5 ${!resolved&&time.overdue?'border-red-700':'border-gray-700'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-blue-900/50 px-2 py-1 text-[10px] font-bold uppercase text-blue-300">{item.entity_type}</span><span className="text-xs text-gray-400">{item.correction_type.replaceAll('_',' ')}</span>{!resolved&&<span className={`inline-flex items-center gap-1 rounded px-2 py-1 text-[10px] font-bold ${time.overdue?'bg-red-950 text-red-300':'bg-amber-950/60 text-amber-300'}`}>{time.overdue?<AlertTriangle className="h-3 w-3"/>:<Clock3 className="h-3 w-3"/>}{time.label}</span>}{resolved&&<span className="inline-flex items-center gap-1 rounded bg-emerald-950/60 px-2 py-1 text-[10px] font-bold text-emerald-300"><CheckCircle2 className="h-3 w-3"/>Resolved</span>}</div><h2 className="mt-2 font-semibold text-white">{item.entity_name}</h2></div><select aria-label={`Status for ${item.entity_name}`} value={item.status} disabled={busy===item.id} onChange={e=>void change(item,e.target.value)} className="min-h-11 rounded-lg border border-gray-600 bg-gray-700 px-3 text-xs disabled:opacity-50"><option value="pending">Pending</option><option value="reviewing">Reviewing</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option></select></div><p className="mt-4 whitespace-pre-line text-sm leading-6 text-gray-300">{item.details}</p>{item.source_url&&<a href={item.source_url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex min-h-11 items-center gap-1 text-xs font-semibold text-blue-400">Open supporting source <ExternalLink className="h-3 w-3"/></a>}{item.resolution_notes&&<div className="mt-3 rounded-lg bg-gray-900/60 p-3 text-xs leading-5 text-gray-300"><strong className="text-gray-100">Resolution:</strong> {item.resolution_notes}</div>}<div className="mt-4 border-t border-gray-700 pt-3 text-xs leading-5 text-gray-500">Reported by {item.reporter_name||'Anonymous'} ({item.reporter_role||'unknown role'}) · {item.reporter_email}<br/>{new Date(item.created_at).toLocaleString('en-NP')} · target {time.targetHours}h</div></article>})}{!shown.length&&<p className="rounded-xl border border-gray-700 bg-gray-800 p-8 text-sm text-gray-500">No reports in this view.</p>}</div></>}
    {loading&&<p className="py-16 text-gray-500">Loading reports…</p>}
  </div>
}
