'use client'

import { useEffect, useState } from 'react'
import { ExternalLink, Flag } from 'lucide-react'

type Correction = { id: string; entity_type: 'school' | 'college'; entity_id: string; entity_name: string; correction_type: string; details: string; source_url: string | null; reporter_name: string | null; reporter_email: string; reporter_role: string | null; status: string; created_at: string }

export default function CorrectionsPage() {
  const [items, setItems] = useState<Correction[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { fetch('/api/admin/corrections', { cache: 'no-store' }).then(async (r) => { const d = await r.json(); if (!r.ok) throw new Error(d.error); setItems(d) }).catch((e) => setError(e.message)).finally(() => setLoading(false)) }, [])
  async function change(item: Correction, status: string) { const r = await fetch(`/api/admin/corrections/${item.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); if (!r.ok) return setError('Update failed.'); const updated = await r.json(); setItems((all) => all.map((x) => x.id === updated.id ? updated : x)) }
  const pending = items.filter((i) => !['accepted', 'rejected'].includes(i.status)); const resolved = items.filter((i) => ['accepted', 'rejected'].includes(i.status))
  const Card = ({ item }: { item: Correction }) => <article className="rounded-xl border border-gray-700 bg-gray-800 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="rounded bg-blue-900/50 px-2 py-1 text-[10px] font-bold uppercase text-blue-300">{item.entity_type}</span><span className="text-xs text-gray-500">{item.correction_type.replaceAll('_', ' ')}</span></div><h2 className="mt-2 font-semibold text-white">{item.entity_name}</h2></div><select value={item.status} onChange={(e) => change(item, e.target.value)} className="rounded-lg border border-gray-600 bg-gray-700 px-3 py-2 text-xs"><option value="pending">Pending</option><option value="reviewing">Reviewing</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option></select></div><p className="mt-4 whitespace-pre-line text-sm leading-6 text-gray-300">{item.details}</p>{item.source_url && <a href={item.source_url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-blue-400">Supporting source <ExternalLink className="h-3 w-3" /></a>}<div className="mt-4 border-t border-gray-700 pt-3 text-xs text-gray-500">Reported by {item.reporter_name || 'Anonymous'} ({item.reporter_role || 'unknown role'}) · {item.reporter_email} · {new Date(item.created_at).toLocaleDateString()}</div></article>
  return <div className="p-8 text-gray-100"><h1 className="flex items-center gap-2 text-2xl font-bold"><Flag className="h-6 w-6 text-orange-400" />Data corrections</h1><p className="mt-1 text-sm text-gray-400">Verify every report against a reliable source before changing public information.</p>{error && <p className="mt-5 rounded-lg bg-red-950/50 p-3 text-red-300">{error}</p>}{loading ? <p className="py-16 text-gray-500">Loading reports…</p> : <><h2 className="mb-3 mt-8 text-sm font-bold uppercase tracking-wider text-gray-400">Needs attention ({pending.length})</h2><div className="grid gap-4 xl:grid-cols-2">{pending.map((item) => <Card key={item.id} item={item} />)}{!pending.length && <p className="text-sm text-gray-500">No pending reports.</p>}</div>{resolved.length > 0 && <><h2 className="mb-3 mt-10 text-sm font-bold uppercase tracking-wider text-gray-400">Resolved ({resolved.length})</h2><div className="grid gap-4 opacity-70 xl:grid-cols-2">{resolved.map((item) => <Card key={item.id} item={item} />)}</div></>}</>}</div>
}

