'use client'

import { useEffect, useMemo, useState } from 'react'
import { ExternalLink, Plus, ShieldCheck } from 'lucide-react'

type College={id:string;name:string;slug:string}
type Evidence={id:string;college_id:string;field_key:string;claim_summary:string;source_name:string;source_url:string;checked_at:string;confidence_score:number;verification_status:string;extraction_method:string;superseded_at:string|null;college:College|null}
const fields=['affiliation','programs','fee','admission_deadline','scholarship','result','facilities','contact']
const blank={college_id:'',field_key:'affiliation',claim_summary:'',source_name:'',source_url:'',confidence_score:80,extraction_method:'manual'}

export default function EvidencePage(){
  const [items,setItems]=useState<Evidence[]>([]),[colleges,setColleges]=useState<College[]>([]),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[setup,setSetup]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('current')
  useEffect(()=>{Promise.all([fetch('/api/admin/evidence',{cache:'no-store'}),fetch('/api/admin/colleges',{cache:'no-store'})]).then(async([e,c])=>{const ed=await e.json(),cd=await c.json();if(!e.ok)throw new Error(ed.error);if(!c.ok)throw new Error(cd.error);setItems(ed.items||[]);setSetup(Boolean(ed.setupRequired));setColleges((cd||[]).filter((x:{status:string|null})=>x.status==='active'||x.status==null).sort((a:College,b:College)=>a.name.localeCompare(b.name)))}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[])
  const shown=useMemo(()=>items.filter(i=>filter==='all'||(filter==='current'?!i.superseded_at:i.verification_status===filter&&!i.superseded_at)),[items,filter])
  const set=<K extends keyof typeof blank>(key:K,value:(typeof blank)[K])=>setForm(old=>({...old,[key]:value}))
  async function create(event:React.FormEvent){event.preventDefault();setSaving(true);setError('');const response=await fetch('/api/admin/evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}),data=await response.json();setSaving(false);if(!response.ok)return setError(data.error||'Could not create evidence.');setItems(old=>[data,...old]);setForm(blank)}
  async function update(item:Evidence,body:object){setError('');const response=await fetch(`/api/admin/evidence/${item.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)return setError(data.error||'Update failed.');setItems(old=>old.map(x=>x.id===item.id?data:x))}
  if(loading)return <div className="p-8 text-gray-400">Loading evidence ledger…</div>
  if(setup)return <div className="p-8 text-gray-100"><h1 className="text-2xl font-bold">Evidence Ledger setup required</h1><p className="mt-3 rounded-xl border border-amber-800 bg-amber-950/40 p-5 text-amber-200">Run <code>20261008_college_evidence_ledger.sql</code> in Supabase, then reload this page.</p></div>
  return <div className="p-5 text-gray-100 sm:p-8"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><ShieldCheck className="h-6 w-6 text-emerald-400"/>College Evidence Ledger</h1><p className="mt-1 max-w-3xl text-sm text-gray-400">Verify individual claims. Publishing evidence never changes college ranking, sponsorship or review scores.</p></div>{error&&<p role="alert" className="mt-5 rounded-lg bg-red-950/50 p-3 text-red-300">{error}</p>}
    <form onSubmit={create} className="mt-6 rounded-xl border border-gray-700 bg-gray-800 p-5"><h2 className="flex items-center gap-2 font-bold"><Plus className="h-4 w-4"/>Add evidence</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-gray-400">College<select required value={form.college_id} onChange={e=>set('college_id',e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-600 bg-gray-900 px-3 text-sm text-white"><option value="">Choose college</option>{colleges.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs text-gray-400">Field<select value={form.field_key} onChange={e=>set('field_key',e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-600 bg-gray-900 px-3 text-sm text-white">{fields.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><label className="text-xs text-gray-400 sm:col-span-2">Exact claim<textarea required minLength={3} maxLength={500} value={form.claim_summary} onChange={e=>set('claim_summary',e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-gray-600 bg-gray-900 p-3 text-sm text-white" placeholder="Describe only what this source proves."/></label><label className="text-xs text-gray-400">Source name<input required value={form.source_name} onChange={e=>set('source_name',e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-600 bg-gray-900 px-3 text-sm text-white"/></label><label className="text-xs text-gray-400">HTTPS source URL<input required type="url" value={form.source_url} onChange={e=>set('source_url',e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-600 bg-gray-900 px-3 text-sm text-white"/></label><label className="text-xs text-gray-400">Extraction confidence (not college quality)<input type="number" min="0" max="100" value={form.confidence_score} onChange={e=>set('confidence_score',Number(e.target.value))} className="mt-1 min-h-11 w-full rounded-lg border border-gray-600 bg-gray-900 px-3 text-sm text-white"/></label><label className="text-xs text-gray-400">Method<select value={form.extraction_method} onChange={e=>set('extraction_method',e.target.value)} className="mt-1 min-h-11 w-full rounded-lg border border-gray-600 bg-gray-900 px-3 text-sm text-white"><option value="manual">Manual</option><option value="structured_import">Structured import</option><option value="automated_extraction">Automated extraction</option></select></label></div><button disabled={saving} className="mt-4 min-h-11 rounded-lg bg-emerald-700 px-4 text-sm font-bold disabled:opacity-50">{saving?'Saving…':'Save as pending'}</button></form>
    <div className="mt-6 flex gap-2 overflow-x-auto">{['current','pending','source_verified','editor_verified','rejected','all'].map(x=><button key={x} onClick={()=>setFilter(x)} className={`min-h-11 whitespace-nowrap rounded-lg px-3 text-xs font-bold capitalize ${filter===x?'bg-blue-600':'border border-gray-700 bg-gray-800 text-gray-300'}`}>{x.replaceAll('_',' ')}</button>)}</div>
    <div className="mt-5 grid gap-4 xl:grid-cols-2">{shown.map(item=><article key={item.id} className={`rounded-xl border bg-gray-800 p-5 ${item.superseded_at?'border-gray-800 opacity-60':'border-gray-700'}`}><div className="flex flex-wrap items-center gap-2"><span className="rounded bg-blue-950 px-2 py-1 text-[10px] font-bold uppercase text-blue-300">{item.field_key.replaceAll('_',' ')}</span><span className="rounded bg-gray-700 px-2 py-1 text-[10px] font-bold uppercase text-gray-300">{item.verification_status.replaceAll('_',' ')}</span><span className="text-xs text-gray-500">confidence {item.confidence_score}%</span></div><h2 className="mt-2 font-bold">{item.college?.name||'Unknown college'}</h2><p className="mt-2 text-sm leading-6 text-gray-300">{item.claim_summary}</p><a href={item.source_url} target="_blank" rel="noopener noreferrer" className="mt-2 inline-flex min-h-11 items-center gap-1 text-xs font-bold text-blue-400">{item.source_name}<ExternalLink className="h-3 w-3"/></a><div className="mt-3 flex flex-wrap gap-2 border-t border-gray-700 pt-3">{!item.superseded_at&&<><button onClick={()=>void update(item,{verification_status:'source_verified'})} className="min-h-10 rounded border border-emerald-700 px-3 text-xs font-bold text-emerald-300">Source verified</button><button onClick={()=>void update(item,{verification_status:'editor_verified'})} className="min-h-10 rounded border border-blue-700 px-3 text-xs font-bold text-blue-300">Editor verified</button><button onClick={()=>void update(item,{verification_status:'rejected'})} className="min-h-10 rounded border border-red-800 px-3 text-xs font-bold text-red-300">Reject</button><button onClick={()=>void update(item,{action:'supersede'})} className="min-h-10 rounded border border-gray-600 px-3 text-xs font-bold text-gray-300">Supersede</button></>}</div></article>)}{!shown.length&&<p className="rounded-xl border border-gray-700 bg-gray-800 p-8 text-gray-500">No evidence in this view.</p>}</div>
  </div>
}
