'use client'

import { useEffect, useState } from 'react'
import { Activity, AlertTriangle, CheckCircle2, ExternalLink, ShieldCheck } from 'lucide-react'

type Source = { id: string; name: string; base_url: string; source_type: string; trust_level: number; permitted_targets: string[]; requires_review: boolean; last_success_at: string | null; consecutive_failures: number; last_error: string | null; robots_reviewed_at: string | null; terms_reviewed_at: string | null }
const date = (value: string | null) => value ? new Date(value).toLocaleString('en-NP', { dateStyle: 'medium', timeStyle: 'short' }) : 'Never'

export default function SourcesPage() {
  const [sources, setSources] = useState<Source[]>([])
  const [error, setError] = useState('')
  useEffect(() => { fetch('/api/admin/sources', { cache: 'no-store' }).then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setSources(data) }).catch(reason => setError(reason.message)) }, [])
  return <div className="p-8 text-gray-100"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Activity className="h-6 w-6 text-cyan-400" />Source health</h1><p className="mt-1 text-sm text-gray-400">Monitor official sources used by automated collection. A high trust score never bypasses editorial rules.</p></div><div className="rounded-lg bg-gray-800 px-3 py-2 text-sm text-gray-400">{sources.length} registered sources</div></div>{error && <p className="mt-5 rounded-lg bg-red-950/50 p-3 text-red-300">{error}</p>}<div className="mt-6 grid gap-4 xl:grid-cols-2">{sources.map(source => <article key={source.id} className="rounded-xl border border-gray-700 bg-gray-800 p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-white">{source.name}</h2>{source.consecutive_failures ? <span className="inline-flex items-center gap-1 rounded bg-red-950/60 px-2 py-1 text-[10px] font-bold uppercase text-red-300"><AlertTriangle className="h-3 w-3" />{source.consecutive_failures} failures</span> : <span className="inline-flex items-center gap-1 rounded bg-emerald-950/60 px-2 py-1 text-[10px] font-bold uppercase text-emerald-300"><CheckCircle2 className="h-3 w-3" />Healthy</span>}</div><p className="mt-1 text-xs text-gray-500">{source.source_type} · trust {source.trust_level}/100 · {source.requires_review ? 'review required' : 'review policy not set'}</p></div><a href={source.base_url} target="_blank" rel="noopener noreferrer" className="text-blue-400"><ExternalLink className="h-4 w-4" /></a></div><div className="mt-4 grid grid-cols-2 gap-3 text-xs"><div className="rounded bg-gray-900/60 p-3"><p className="text-gray-500">Last success</p><p className="mt-1 text-gray-200">{date(source.last_success_at)}</p></div><div className="rounded bg-gray-900/60 p-3"><p className="text-gray-500">Allowed content</p><p className="mt-1 text-gray-200">{source.permitted_targets?.join(', ') || 'Not configured'}</p></div></div>{source.last_error && <p className="mt-3 rounded bg-red-950/30 p-2 text-xs leading-5 text-red-200">Latest failure: {source.last_error}</p>}<p className="mt-3 flex items-center gap-1.5 text-xs text-gray-500"><ShieldCheck className="h-3.5 w-3.5 text-gray-400" />Robots review: {date(source.robots_reviewed_at)} · Terms review: {date(source.terms_reviewed_at)}</p></article>)}</div>{!sources.length && !error && <p className="py-20 text-center text-gray-500">No sources have been registered yet. The scraper will register a source when it first collects content.</p>}</div>
}
