'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { AlertTriangle, BarChart3, CheckCircle2, Clock3, Search } from 'lucide-react'
import { evidenceFreshness } from '@/lib/evidence-freshness'

type College={id:string;name:string;slug:string;status:string|null;verification_status:string|null;last_verified_at:string|null}
type Evidence={id:string;college_id:string;field_key:string;checked_at:string;verification_status:string;superseded_at:string|null}
const required=['affiliation','programs','fee','contact']
const seasonal=['admission_deadline','scholarship']
const labels:Record<string,string>={affiliation:'Affiliation',programs:'Programmes',fee:'Fees',contact:'Contact',admission_deadline:'Admission deadline',scholarship:'Scholarship'}

export default function EvidenceCoveragePage(){
  const [colleges,setColleges]=useState<College[]>([]),[evidence,setEvidence]=useState<Evidence[]>([]),[loading,setLoading]=useState(true),[setup,setSetup]=useState(false),[error,setError]=useState(''),[search,setSearch]=useState(''),[view,setView]=useState<'gaps'|'complete'|'all'>('gaps')
  useEffect(()=>{Promise.all([fetch('/api/admin/colleges',{cache:'no-store'}),fetch('/api/admin/evidence',{cache:'no-store'})]).then(async([c,e])=>{const cd=await c.json(),ed=await e.json();if(!c.ok)throw new Error(cd.error);if(!e.ok)throw new Error(ed.error);setColleges((cd||[]).filter((x:College)=>x.status==='active'||x.status==null));setEvidence(ed.items||[]);setSetup(Boolean(ed.setupRequired))}).catch(reason=>setError(reason.message)).finally(()=>setLoading(false))},[])
  const rows=useMemo(()=>colleges.map(college=>{const current=evidence.filter(item=>item.college_id===college.id&&!item.superseded_at&&['source_verified','editor_verified'].includes(item.verification_status)),keys=new Set(current.map(item=>item.field_key)),missing=required.filter(key=>!keys.has(key)),stale=current.filter(item=>evidenceFreshness(item.field_key,item.checked_at).stale),seasonalAvailable=seasonal.filter(key=>keys.has(key)),coverage=Math.round(((required.length-missing.length)/required.length)*100);return {college,current,missing,stale,seasonalAvailable,coverage}}).filter(row=>row.college.name.toLowerCase().includes(search.toLowerCase().trim())).filter(row=>view==='all'||(view==='complete'?row.missing.length===0:row.missing.length>0||row.stale.length>0)).sort((a,b)=>a.coverage-b.coverage||b.stale.length-a.stale.length||a.college.name.localeCompare(b.college.name)).slice(0,50),[colleges,evidence,search,view])
  const activeEvidence=evidence.filter(item=>!item.superseded_at&&['source_verified','editor_verified'].includes(item.verification_status)),completeCount=colleges.filter(college=>required.every(key=>activeEvidence.some(item=>item.college_id===college.id&&item.field_key===key))).length,staleCount=activeEvidence.filter(item=>evidenceFreshness(item.field_key,item.checked_at).stale).length,coveredCorePairs=new Set(activeEvidence.filter(item=>required.includes(item.field_key)).map(item=>`${item.college_id}:${item.field_key}`)).size,overall=colleges.length?Math.round(coveredCorePairs/(colleges.length*required.length)*100):0
  if(loading)return <div className="p-8 text-gray-400">Building evidence coverage audit…</div>
  if(setup)return <div className="p-8 text-gray-100"><h1 className="text-2xl font-bold">Evidence audit setup required</h1><p className="mt-4 rounded-xl border border-amber-800 bg-amber-950/40 p-5 text-amber-200">Run <code>20261008_college_evidence_ledger.sql</code>, then reload.</p></div>
  return <div className="p-5 text-gray-100 sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><BarChart3 className="h-6 w-6 text-cyan-400"/>College evidence coverage</h1><p className="mt-1 max-w-3xl text-sm text-gray-400">Operational audit of the first 50 highest-risk gaps. Coverage measures documented evidence—not college quality.</p></div><Link href="/admin/evidence" className="min-h-11 rounded-lg bg-blue-600 px-4 py-3 text-sm font-bold">Add evidence</Link></div>{error&&<p role="alert" className="mt-5 rounded-lg bg-red-950/50 p-3 text-red-300">{error}</p>}
    <section className="mt-7 grid gap-3 sm:grid-cols-4" aria-label="Evidence coverage summary"><div className="rounded-xl border border-gray-700 bg-gray-800 p-4"><p className="text-xs uppercase text-gray-500">Active colleges</p><p className="mt-2 text-2xl font-bold">{colleges.length}</p></div><div className="rounded-xl border border-gray-700 bg-gray-800 p-4"><p className="text-xs uppercase text-gray-500">Core coverage</p><p className="mt-2 text-2xl font-bold text-cyan-300">{Math.min(100,overall)}%</p></div><div className="rounded-xl border border-gray-700 bg-gray-800 p-4"><p className="text-xs uppercase text-gray-500">Core complete</p><p className="mt-2 text-2xl font-bold text-emerald-300">{completeCount}</p></div><div className="rounded-xl border border-gray-700 bg-gray-800 p-4"><p className="text-xs uppercase text-gray-500">Stale claims</p><p className="mt-2 text-2xl font-bold text-amber-300">{staleCount}</p></div></section>
    <div className="mt-6 flex flex-wrap gap-3"><label className="relative min-w-64 flex-1"><span className="sr-only">Search colleges</span><Search className="absolute left-3 top-3.5 h-4 w-4 text-gray-500"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search college…" className="min-h-11 w-full rounded-lg border border-gray-700 bg-gray-800 pl-10 pr-3 text-sm"/></label><div className="flex gap-2">{(['gaps','complete','all'] as const).map(option=><button key={option} onClick={()=>setView(option)} aria-pressed={view===option} className={`min-h-11 rounded-lg px-4 text-sm font-bold capitalize ${view===option?'bg-blue-600':'border border-gray-700 bg-gray-800 text-gray-300'}`}>{option}</button>)}</div></div>
    <div className="mt-5 overflow-hidden rounded-xl border border-gray-700"><div className="hidden grid-cols-[minmax(220px,1.4fr)_100px_minmax(240px,1fr)_120px] gap-4 bg-gray-900 px-5 py-3 text-xs font-bold uppercase text-gray-500 md:grid"><span>College</span><span>Coverage</span><span>Missing or stale</span><span>Action</span></div>{rows.map(row=><article key={row.college.id} className="grid gap-3 border-t border-gray-700 bg-gray-800 p-5 first:border-t-0 md:grid-cols-[minmax(220px,1.4fr)_100px_minmax(240px,1fr)_120px] md:items-center"><div><Link href={`/colleges/${row.college.slug}`} target="_blank" className="font-bold text-white hover:text-blue-300">{row.college.name}</Link><p className="mt-1 text-xs text-gray-500">{row.current.length} verified claim{row.current.length===1?'':'s'}{row.seasonalAvailable.length?` · ${row.seasonalAvailable.length} seasonal`:''}</p></div><div><span className={`font-mono text-lg font-bold ${row.coverage===100?'text-emerald-300':row.coverage>=50?'text-amber-300':'text-red-300'}`}>{row.coverage}%</span></div><div className="flex flex-wrap gap-1.5">{row.missing.map(key=><span key={key} className="inline-flex items-center gap-1 rounded bg-red-950/60 px-2 py-1 text-[10px] font-bold text-red-300"><AlertTriangle className="h-3 w-3"/>{labels[key]}</span>)}{row.stale.map(item=><span key={item.id} className="inline-flex items-center gap-1 rounded bg-amber-950/60 px-2 py-1 text-[10px] font-bold text-amber-300"><Clock3 className="h-3 w-3"/>{labels[item.field_key]||item.field_key} stale</span>)}{!row.missing.length&&!row.stale.length&&<span className="inline-flex items-center gap-1 text-xs font-bold text-emerald-300"><CheckCircle2 className="h-4 w-4"/>Core evidence current</span>}</div><Link href="/admin/evidence" className="inline-flex min-h-10 items-center justify-center rounded border border-blue-700 px-3 text-xs font-bold text-blue-300">Review</Link></article>)}{!rows.length&&<p className="bg-gray-800 p-10 text-center text-sm text-gray-500">No colleges match this audit view.</p>}</div>
    <p className="mt-4 text-xs leading-5 text-gray-500">Core coverage requires affiliation, programmes, fees and contact evidence. Admission and scholarship evidence is tracked separately because it is seasonal.</p>
  </div>
}
