export type Career = {
  slug: string
  title: string
  summary: string
  category: string
  studyRoutes: string[]
  eligibility: string
  entrance: string[]
  skills: string[]
  roles: string[]
  portfolioIdeas: string[]
  sourceName: string
  sourceUrl: string
}

const source = { sourceName: 'Official Nepal education and professional-body sources', sourceUrl: 'https://moest.gov.np/' }

export const careers: Career[] = [
  { slug: 'software-developer', title: 'Software Developer', category: 'Technology', summary: 'Build websites, mobile apps, systems and digital products for organisations and customers.', studyRoutes: ['+2 Science or Management with Mathematics', 'Bachelor in Computer Science, IT, Software Engineering or BIT', 'Practical projects alongside formal study'], eligibility: 'Requirements differ by institution; mathematics is commonly expected for science and engineering routes.', entrance: ['University entrance or college-specific test', 'Some programs assess mathematics and English'], skills: ['Programming fundamentals', 'Problem solving', 'Git and teamwork', 'Clear written communication'], roles: ['Junior developer', 'QA engineer', 'Web developer', 'Support engineer'], portfolioIdeas: ['Build a useful Nepal-focused web tool', 'Contribute to an open-source project', 'Publish two documented case studies'], ...source },
  { slug: 'nurse', title: 'Nurse', category: 'Health', summary: 'Provide direct patient care, health education and clinical support in hospitals and communities.', studyRoutes: ['+2 Science (Biology route)', 'PCL Nursing, BN or BSc Nursing', 'Clinical placement and professional registration'], eligibility: 'Science and biology requirements apply; confirm current criteria with the institution and Nepal Nursing Council.', entrance: ['Institution or university entrance examination', 'Health-science selection process'], skills: ['Patient communication', 'Clinical observation', 'Documentation', 'Teamwork under pressure'], roles: ['Staff nurse', 'Community nurse', 'Clinical educator', 'Public-health nurse'], portfolioIdeas: ['Maintain supervised clinical learning reflections', 'Volunteer in approved health-awareness programmes', 'Document CPD certificates'], sourceName: 'Nepal Nursing Council', sourceUrl: 'https://nnc.org.np/' },
  { slug: 'chartered-accountant', title: 'Chartered Accountant', category: 'Business', summary: 'Work with financial reporting, audit, tax, controls and business decision-making.', studyRoutes: ['+2 Management, Science or equivalent', 'CAP/Foundation pathway', 'CA professional levels and articleship'], eligibility: 'Entry rules are set by the Institute of Chartered Accountants of Nepal and can change by intake.', entrance: ['ICAN entry assessment where applicable', 'Professional examinations by level'], skills: ['Accounting basics', 'Excel and financial analysis', 'Attention to detail', 'Professional ethics'], roles: ['Audit associate', 'Tax associate', 'Financial analyst', 'Accountant'], portfolioIdeas: ['Create sample financial statements', 'Complete an Excel reporting project', 'Document relevant training'], sourceName: 'Institute of Chartered Accountants of Nepal', sourceUrl: 'https://ican.org.np/' },
  { slug: 'civil-engineer', title: 'Civil Engineer', category: 'Engineering', summary: 'Plan, design and help deliver buildings, roads, water systems and other infrastructure.', studyRoutes: ['+2 Science with Physics and Mathematics', 'BE Civil Engineering or Diploma in Civil Engineering', 'Field experience and professional development'], eligibility: 'Physics and mathematics are standard for engineering routes; verify the latest institution notice.', entrance: ['Engineering entrance examination', 'Institution-specific selection'], skills: ['Mathematics', 'AutoCAD or design tools', 'Site communication', 'Safety awareness'], roles: ['Site engineer', 'Design engineer', 'Estimator', 'Project coordinator'], portfolioIdeas: ['Prepare a small site-plan case study', 'Learn CAD through a documented drawing set', 'Join an approved field visit or competition'], sourceName: 'Nepal Engineering Council', sourceUrl: 'https://nec.gov.np/' },
  { slug: 'teacher', title: 'Teacher', category: 'Education', summary: 'Help learners build understanding, confidence and practical capabilities in classrooms and communities.', studyRoutes: ['+2 in a relevant stream', 'Bachelor or Master of Education / subject degree with pedagogy', 'Teaching practice and licensing where required'], eligibility: 'Subject, level and employer requirements vary. Check university and local recruitment notices.', entrance: ['University entrance where required', 'Teaching licence or recruitment assessment for relevant roles'], skills: ['Lesson planning', 'Communication', 'Inclusive teaching', 'Digital learning tools'], roles: ['School teacher', 'Subject teacher', 'Learning facilitator', 'Education coordinator'], portfolioIdeas: ['Create sample lesson plans', 'Document tutoring or classroom practice', 'Build simple learning resources'], ...source },
  { slug: 'graphic-designer', title: 'Graphic Designer', category: 'Creative', summary: 'Use visual communication to create brands, digital content, publications and campaigns.', studyRoutes: ['+2 in any stream', 'Bachelor or diploma in design, multimedia or related field', 'Portfolio-led practice'], eligibility: 'Creative programmes may use a portfolio, interview or aptitude review in addition to academic eligibility.', entrance: ['Portfolio or aptitude review', 'Institution-specific test or interview'], skills: ['Typography', 'Adobe or open-source design tools', 'Visual storytelling', 'Client communication'], roles: ['Graphic designer', 'Brand designer', 'UI designer', 'Content designer'], portfolioIdeas: ['Create three brand identity case studies', 'Redesign a public-information poster', 'Publish process notes, not just final images'], ...source },
  { slug: 'agriculture-officer', title: 'Agriculture Officer', category: 'Agriculture', summary: 'Support farming productivity, food systems, extension services and rural enterprise.', studyRoutes: ['+2 Science or agriculture stream', 'BSc Agriculture, veterinary-related or diploma route', 'Field placements and extension work'], eligibility: 'Science or agriculture prerequisites are common; check the institution and faculty notice.', entrance: ['Agriculture or university entrance test', 'Institution-specific selection'], skills: ['Crop and soil basics', 'Field observation', 'Data collection', 'Community communication'], roles: ['Agriculture technician', 'Extension officer', 'Farm manager', 'Agribusiness associate'], portfolioIdeas: ['Document a small crop trial', 'Create a farm-budget model', 'Join an agriculture innovation challenge'], ...source },
  { slug: 'data-analyst', title: 'Data Analyst', category: 'Technology', summary: 'Turn data into clear findings that help teams make better decisions.', studyRoutes: ['+2 with mathematics or statistics where possible', 'Bachelor in IT, statistics, economics, business analytics or related area', 'Hands-on data projects'], eligibility: 'Requirements differ; strengthen mathematics, statistics and English before applying.', entrance: ['University or college entrance', 'Some technical programmes assess mathematics'], skills: ['Spreadsheets and SQL', 'Statistics basics', 'Data visualisation', 'Clear explanation of findings'], roles: ['Data analyst', 'MIS officer', 'Research assistant', 'Business analyst'], portfolioIdeas: ['Analyse a public Nepal dataset', 'Build a clear dashboard', 'Write a one-page insight report'], ...source },
  { slug: 'medical-doctor', title: 'Medical Doctor', category: 'Health', summary: 'Diagnose, treat and help prevent illness through clinical practice and continuing learning.', studyRoutes: ['+2 Science with Biology', 'MBBS', 'Internship and Nepal Medical Council registration'], eligibility: 'Strict science requirements and national admission processes apply. Check current official notices before preparing.', entrance: ['Medical education entrance examination', 'Merit-based admission process'], skills: ['Biology and scientific reasoning', 'Patient communication', 'Ethics', 'Resilience and teamwork'], roles: ['Medical officer', 'Resident doctor', 'General practitioner', 'Public-health clinician'], portfolioIdeas: ['Document approved service or health-camp experience', 'Keep a learning reflection journal', 'Take verified first-aid training'], sourceName: 'Nepal Medical Council', sourceUrl: 'https://nmc.org.np/' },
  { slug: 'architect', title: 'Architect', category: 'Design & Engineering', summary: 'Design practical, safe and meaningful buildings and spaces.', studyRoutes: ['+2 Science with Mathematics', 'Bachelor of Architecture', 'Studio work and supervised practical experience'], eligibility: 'Mathematics and science prerequisites are usually required; architecture may also assess design aptitude.', entrance: ['Engineering or architecture entrance', 'Aptitude or portfolio assessment where required'], skills: ['Design thinking', 'Drawing and model-making', 'CAD/BIM tools', 'Presentation'], roles: ['Architectural assistant', 'Junior architect', 'Interior designer', 'Urban design assistant'], portfolioIdeas: ['Create a small spatial design portfolio', 'Document models and sketches', 'Analyse a local public space'], sourceName: 'Nepal Engineering Council', sourceUrl: 'https://nec.gov.np/' },
  { slug: 'lawyer', title: 'Lawyer', category: 'Law', summary: 'Interpret law, advise clients and support justice through research, advocacy and negotiation.', studyRoutes: ['+2 in any stream', 'BA LLB, LLB or related law programme', 'Professional licensing process'], eligibility: 'Entry and licensing requirements depend on the programme and Nepal Bar Council rules.', entrance: ['Law entrance examination where required', 'Institution-specific assessment'], skills: ['Research', 'Writing', 'Public speaking', 'Ethics and judgement'], roles: ['Legal associate', 'Advocate', 'Compliance officer', 'Policy researcher'], portfolioIdeas: ['Write a case-note summary', 'Join a moot-court or debate', 'Create a legal-research sample'], sourceName: 'Nepal Bar Council', sourceUrl: 'https://nepalbarcouncil.org.np/' },
  { slug: 'pharmacist', title: 'Pharmacist', category: 'Health', summary: 'Ensure medicines are used safely and effectively in hospitals, pharmacies and industry.', studyRoutes: ['+2 Science with Biology', 'BPharm or Diploma in Pharmacy', 'Professional registration where required'], eligibility: 'Science requirements and registration rules apply; check the current notice before applying.', entrance: ['Health-science entrance process', 'Institution-specific test'], skills: ['Chemistry and pharmacology basics', 'Accuracy', 'Patient counselling', 'Inventory systems'], roles: ['Hospital pharmacist', 'Community pharmacist', 'Quality-control officer', 'Medical sales associate'], portfolioIdeas: ['Create a medicine-safety awareness resource', 'Document supervised placement learning', 'Study medicine inventory systems'], sourceName: 'Nepal Pharmacy Council', sourceUrl: 'https://nepalpharmacycouncil.org.np/' },
  { slug: 'hotel-manager', title: 'Hotel Manager', category: 'Hospitality', summary: 'Coordinate guest experience, service operations, food and accommodation teams.', studyRoutes: ['+2 in any stream', 'BHM, BTTM or hospitality diploma', 'Industry placement and service experience'], eligibility: 'Most hospitality programmes accept multiple +2 streams; requirements differ by college.', entrance: ['College or university entrance', 'Interview or English assessment where required'], skills: ['Service communication', 'Operations planning', 'Food and safety basics', 'Team leadership'], roles: ['Front-office associate', 'Restaurant supervisor', 'Hotel operations trainee', 'Event coordinator'], portfolioIdeas: ['Document an event plan', 'Build a guest-service case study', 'Keep verified service-training certificates'], ...source },
  { slug: 'electrician', title: 'Electrician', category: 'Technical & TVET', summary: 'Install, test and maintain safe electrical systems in homes, buildings and industry.', studyRoutes: ['SEE or +2 depending on programme', 'CTEVT technical diploma or short skills training', 'Apprenticeship and supervised field work'], eligibility: 'Entry rules vary by CTEVT provider and programme level. Confirm safety and certification requirements.', entrance: ['Programme-specific entrance or selection', 'Practical readiness assessment in some cases'], skills: ['Electrical safety', 'Circuit basics', 'Fault finding', 'Customer communication'], roles: ['Electrical technician', 'Maintenance assistant', 'Solar installation technician', 'Apprentice electrician'], portfolioIdeas: ['Maintain a supervised practical logbook', 'Document safety training', 'Build a simple circuit project'], sourceName: 'Council for Technical Education and Vocational Training', sourceUrl: 'https://ctevt.org.np/' },
  { slug: 'digital-marketer', title: 'Digital Marketer', category: 'Business & Technology', summary: 'Help organisations reach audiences through content, search, social media and measurement.', studyRoutes: ['+2 in any stream', 'Bachelor in marketing, business, IT or related field', 'Short, practical courses and real campaign work'], eligibility: 'There is no single mandatory degree path; employers value evidence of ethical, measurable work.', entrance: ['College entrance where required', 'Portfolio or interview for some roles'], skills: ['Writing', 'Analytics', 'Basic design', 'Ethical advertising'], roles: ['Digital marketing assistant', 'Content coordinator', 'SEO associate', 'Social media executive'], portfolioIdeas: ['Run a transparent sample campaign', 'Create a content calendar', 'Write a campaign-result case study'], ...source },
  { slug: 'lab-technologist', title: 'Medical Lab Technologist', category: 'Health', summary: 'Perform and support accurate laboratory testing that informs clinical decisions.', studyRoutes: ['+2 Science with Biology', 'BMLT, BSc MLT or diploma route', 'Practical laboratory placement'], eligibility: 'Science requirements are standard; check current programme and council requirements.', entrance: ['Health-science or university entrance', 'Institution-specific selection'], skills: ['Laboratory safety', 'Accuracy', 'Documentation', 'Quality control'], roles: ['Lab technologist', 'Laboratory assistant', 'Research technician', 'Quality-control assistant'], portfolioIdeas: ['Maintain approved practical records', 'Create a laboratory-safety summary', 'Join a health-science workshop'], ...source },
  { slug: 'entrepreneur', title: 'Entrepreneur', category: 'Business', summary: 'Identify a problem, build a useful solution and learn to operate a sustainable enterprise.', studyRoutes: ['+2 in any stream', 'Business, technology, agriculture or design programme—depending on the problem area', 'Incubation, mentorship and small real-world experiments'], eligibility: 'There is no single required degree. Choose study and skill routes based on the problem you want to solve.', entrance: ['Programme-specific entry only', 'Startup and incubator selection may use a pitch'], skills: ['Customer research', 'Budgeting', 'Communication', 'Experimentation'], roles: ['Founder', 'Small-business operator', 'Product associate', 'Social enterprise coordinator'], portfolioIdeas: ['Interview ten potential users', 'Test a low-cost prototype', 'Write a one-page business model'], ...source },
  { slug: 'social-worker', title: 'Social Worker', category: 'Community', summary: 'Work with communities and services to support wellbeing, inclusion and social change.', studyRoutes: ['+2 in any stream', 'Bachelor or Master in Social Work / development studies', 'Supervised field placement'], eligibility: 'Programme requirements vary; commitment to ethical community work is essential.', entrance: ['University or college entrance', 'Interview where required'], skills: ['Active listening', 'Community facilitation', 'Report writing', 'Safeguarding awareness'], roles: ['Programme officer', 'Case worker', 'Community mobiliser', 'Research assistant'], portfolioIdeas: ['Document supervised volunteer work', 'Create a community-needs summary', 'Complete safeguarding training'], ...source },
  { slug: 'forestry-officer', title: 'Forestry Officer', category: 'Environment', summary: 'Protect and manage forests, biodiversity and natural resources with communities.', studyRoutes: ['+2 Science or forestry stream', 'BSc Forestry, environmental science or technical route', 'Field research and placement'], eligibility: 'Science or relevant technical background is often required. Check the faculty notice.', entrance: ['University entrance examination', 'Institution-specific selection'], skills: ['Ecology basics', 'Field data collection', 'GIS awareness', 'Community collaboration'], roles: ['Forestry technician', 'Conservation officer', 'Field researcher', 'Environmental project assistant'], portfolioIdeas: ['Map a local green space', 'Document a biodiversity observation project', 'Join a conservation activity'], ...source },
  { slug: 'bank-officer', title: 'Bank Officer', category: 'Finance', summary: 'Support customers, financial operations, lending, risk and digital banking services.', studyRoutes: ['+2 in Management, Science or equivalent', 'Bachelor in BBA, BBS, economics, finance or related area', 'Banking training and recruitment preparation'], eligibility: 'Requirements vary by bank and role; public recruitment notices define specific criteria.', entrance: ['University entrance where required', 'Bank recruitment written test and interview'], skills: ['Numeracy', 'Customer communication', 'Excel', 'Ethics and attention to detail'], roles: ['Trainee assistant', 'Credit officer', 'Operations officer', 'Relationship officer'], portfolioIdeas: ['Build a personal-finance spreadsheet', 'Study a bank annual report', 'Practise a customer-service scenario'], ...source },
]

export const careerBySlug = (slug: string) => careers.find((career) => career.slug === slug)
