'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { CalendarCheck2, ExternalLink, Pencil, Plus, Search, Trash2 } from 'lucide-react'
import ConfirmDialog, { CONFIRM_CLOSED, type ConfirmState } from '@/components/ui/ConfirmDialog'
import { ToastList, useToast } from '@/components/ui/Toast'
import type { Admission } from '@/types'

export default function AdminAdmissionsPage() {
  const [items, setItems] = useState<Admission[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true); const [dialog, setDialog] = useState<ConfirmState>(CONFIRM_CLOSED); const { toasts, toast, dismiss } = useToast()
  useEffect(() => { fetch('/api/admin/admissions', { cache: 'no-store' }).then((r) => r.json()).then((d) => setItems(Array.isArray(d) ? d : [])).catch(() => toast.error('Could not load admissions')).finally(() => setLoading(false)) }, []) // eslint-disable-line react-hooks/exhaustive-deps
  const visible = useMemo(() => items.filter((item) => `${item.title} ${item.institution_name}`.toLowerCase().includes(query.toLowerCase())), [items, query])
  function remove(item: Admission) { setDialog({ isOpen: true, title: 'Delete admission', message: `Delete “${item.title}”? This cannot be undone.`, confirmLabel: 'Delete', variant: 'danger', onConfirm: async () => { setDialog(CONFIRM_CLOSED); const r = await fetch(`/api/admin/admissions/${item.id}`, { method: 'DELETE' }); if (!r.ok) return toast.error('Could not delete admission'); setItems((all) => all.filter((x) => x.id !== item.id)); toast.success('Admission deleted') } }) }
  return <div className="p-8 text-gray-100"><div className="mb-6 flex items-start justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><CalendarCheck2 className="h-6 w-6 text-cyan-400" />Admissions</h1><p className="mt-1 text-sm text-gray-400">{items.length} admission records</p></div><Link href="/admin/admissions/new" className="flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold"><Plus className="h-4 w-4" />Add admission</Link></div><div className="relative mb-5"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-500" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search admissions…" className="w-full rounded-lg border border-gray-700 bg-gray-800 py-2.5 pl-9 pr-4 text-sm outline-none focus:border-blue-500" /></div>{loading ? <p className="py-16 text-center text-gray-500">Loading…</p> : <div className="overflow-hidden rounded-xl border border-gray-700 bg-gray-800"><table className="w-full text-sm"><thead><tr className="border-b border-gray-700 text-left text-gray-400"><th className="px-5 py-3 font-medium">Opportunity</th><th className="px-5 py-3 font-medium">Deadline</th><th className="px-5 py-3 font-medium">Status</th><th className="px-5 py-3 text-right font-medium">Actions</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id} className="border-b border-gray-700/50"><td className="px-5 py-3"><p className="font-medium text-white">{item.title}</p><p className="mt-0.5 text-xs text-gray-500">{item.institution_name}{item.is_sponsored ? ' · Sponsored' : ''}</p></td><td className="px-5 py-3 text-gray-400">{item.application_deadline ? new Date(item.application_deadline).toLocaleDateString() : 'Not announced'}</td><td className="px-5 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase ${item.status === 'published' ? 'bg-emerald-900/50 text-emerald-300' : item.status === 'draft' ? 'bg-amber-900/50 text-amber-300' : 'bg-gray-700 text-gray-300'}`}>{item.status}</span></td><td className="px-5 py-3"><div className="flex justify-end gap-2">{item.status === 'published' && <Link href={`/admissions/${item.slug}`} target="_blank" className="rounded p-2 text-gray-400 hover:bg-gray-700 hover:text-white"><ExternalLink className="h-4 w-4" /></Link>}<Link href={`/admin/admissions/${item.id}/edit`} className="rounded p-2 text-gray-400 hover:bg-gray-700 hover:text-blue-400"><Pencil className="h-4 w-4" /></Link><button onClick={() => remove(item)} className="rounded p-2 text-gray-400 hover:bg-gray-700 hover:text-red-400"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table>{!visible.length && <p className="py-12 text-center text-gray-500">No admissions found.</p>}</div>}<ConfirmDialog {...dialog} onCancel={() => setDialog(CONFIRM_CLOSED)} /><ToastList toasts={toasts} onDismiss={dismiss} /></div>
}

