'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, Save } from 'lucide-react'
import type { Admission } from '@/types'

type FormState = Omit<Admission, 'id' | 'created_at' | 'updated_at' | 'school' | 'college' | 'application_fee' | 'available_seats'> & { application_fee: number | string | null; available_seats: number | string | null }
const EMPTY: FormState = { title: '', slug: '', institution_type: 'college', institution_name: '', school_id: null, college_id: null, programs: [], education_level: '', admission_type: 'general', summary: '', details: '', eligibility: '', required_documents: [], application_open_at: null, application_deadline: null, entrance_exam_at: null, application_fee: '', available_seats: '', application_url: '', contact_phone: '', contact_email: '', source_name: '', source_url: '', verification_status: 'source_verified', last_verified_at: null, status: 'draft', is_featured: false, is_sponsored: false, sponsor_label: '', published_at: null }

function localDate(value: string | null | undefined) { return value ? value.slice(0, 16) : '' }
function lines(value: string) { return value.split(/[,\n]/).map((item) => item.trim()).filter(Boolean) }

export default function AdmissionForm({ initialData, admissionId }: { initialData?: Partial<Admission>; admissionId?: string }) {
  const [form, setForm] = useState<FormState>({ ...EMPTY, ...initialData, application_open_at: localDate(initialData?.application_open_at) || null, application_deadline: localDate(initialData?.application_deadline) || null, entrance_exam_at: localDate(initialData?.entrance_exam_at) || null })
  const [schools, setSchools] = useState<{ id: string; name: string }[]>([]); const [colleges, setColleges] = useState<{ id: string; name: string }[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const router = useRouter()
  useEffect(() => { Promise.all([fetch('/api/admin/schools').then((r) => r.json()), fetch('/api/admin/colleges').then((r) => r.json())]).then(([s, c]) => { setSchools(Array.isArray(s) ? s : []); setColleges(Array.isArray(c) ? c : []) }) }, [])
  function set<K extends keyof FormState>(key: K, value: FormState[K]) { setForm((old) => ({ ...old, [key]: value })) }
  function pickInstitution(value: string) { const [kind, id] = value.split(':'); const source = kind === 'school' ? schools : colleges; const institution = source.find((item) => item.id === id); setForm((old) => ({ ...old, institution_type: kind as Admission['institution_type'], institution_name: institution?.name || '', school_id: kind === 'school' ? id : null, college_id: kind === 'college' ? id : null })) }
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(''); const payload = { ...form, programs: form.programs, required_documents: form.required_documents, application_fee: form.application_fee === '' ? null : Number(form.application_fee), available_seats: form.available_seats === '' ? null : Number(form.available_seats), application_open_at: form.application_open_at || null, application_deadline: form.application_deadline || null, entrance_exam_at: form.entrance_exam_at || null }; const r = await fetch(admissionId ? `/api/admin/admissions/${admissionId}` : '/api/admin/admissions', { method: admissionId ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const d = await r.json(); setSaving(false); if (!r.ok) return setError(d.error || 'Could not save admission.'); router.push('/admin/admissions'); router.refresh() }
  const input = 'w-full rounded-lg border border-gray-600 bg-gray-700 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500'; const label = 'mb-1.5 block text-sm font-medium text-gray-300'
  return <form onSubmit={submit} className="max-w-4xl p-8 text-gray-100"><div className="mb-8 flex items-center gap-3"><button type="button" onClick={() => router.back()} className="rounded-lg p-2 text-gray-400 hover:bg-gray-700"><ArrowLeft className="h-4 w-4" /></button><div><h1 className="text-2xl font-bold text-white">{admissionId ? 'Edit admission' : 'Add admission'}</h1><p className="mt-1 text-sm text-gray-400">Publish only after confirming dates on the original source.</p></div></div>{error && <p className="mb-5 rounded-lg border border-red-800 bg-red-950/50 p-3 text-sm text-red-300">{error}</p>}
    <div className="space-y-6 rounded-xl border border-gray-700 bg-gray-800 p-6"><section className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className={label}>Title *</span><input required value={form.title} onChange={(e) => set('title', e.target.value)} className={input} /></label><label><span className={label}>Linked institution</span><select value={form.school_id ? `school:${form.school_id}` : form.college_id ? `college:${form.college_id}` : ''} onChange={(e) => pickInstitution(e.target.value)} className={input}><option value="">Manual institution</option><optgroup label="Schools">{schools.map((x) => <option key={x.id} value={`school:${x.id}`}>{x.name}</option>)}</optgroup><optgroup label="Colleges">{colleges.map((x) => <option key={x.id} value={`college:${x.id}`}>{x.name}</option>)}</optgroup></select></label><label><span className={label}>Institution name *</span><input required value={form.institution_name} onChange={(e) => set('institution_name', e.target.value)} className={input} /></label><label><span className={label}>Institution type</span><select value={form.institution_type} onChange={(e) => set('institution_type', e.target.value as Admission['institution_type'])} className={input}><option value="school">School</option><option value="college">College</option><option value="university">University</option><option value="training_provider">Training provider</option><option value="other">Other</option></select></label><label><span className={label}>Education level</span><select value={form.education_level || ''} onChange={(e) => set('education_level', e.target.value)} className={input}><option value="">Choose level</option><option>SEE</option><option>+2</option><option>Diploma</option><option>Bachelor</option><option>Master</option></select></label><label><span className={label}>Admission type</span><select value={form.admission_type} onChange={(e) => set('admission_type', e.target.value as Admission['admission_type'])} className={input}><option value="general">General</option><option value="entrance">Entrance</option><option value="scholarship">Scholarship</option><option value="quota">Quota</option><option value="transfer">Transfer</option><option value="other">Other</option></select></label><label><span className={label}>Programs (comma or line separated)</span><textarea value={form.programs.join('\n')} onChange={(e) => set('programs', lines(e.target.value))} rows={3} className={input} /></label></section>
      <section className="grid gap-4 sm:grid-cols-3"><label><span className={label}>Opens</span><input type="datetime-local" value={localDate(form.application_open_at)} onChange={(e) => set('application_open_at', e.target.value)} className={input} /></label><label><span className={label}>Deadline</span><input type="datetime-local" value={localDate(form.application_deadline)} onChange={(e) => set('application_deadline', e.target.value)} className={input} /></label><label><span className={label}>Entrance exam</span><input type="datetime-local" value={localDate(form.entrance_exam_at)} onChange={(e) => set('entrance_exam_at', e.target.value)} className={input} /></label><label><span className={label}>Application fee (NPR)</span><input type="number" min="0" value={form.application_fee ?? ''} onChange={(e) => set('application_fee', e.target.value)} className={input} /></label><label><span className={label}>Seats</span><input type="number" min="0" value={form.available_seats ?? ''} onChange={(e) => set('available_seats', e.target.value)} className={input} /></label><label><span className={label}>Application URL</span><input type="url" value={form.application_url || ''} onChange={(e) => set('application_url', e.target.value)} className={input} /></label></section>
      <section className="space-y-4"><label><span className={label}>Short summary</span><textarea value={form.summary || ''} onChange={(e) => set('summary', e.target.value)} rows={2} maxLength={500} className={input} /></label><label><span className={label}>Full details</span><textarea value={form.details || ''} onChange={(e) => set('details', e.target.value)} rows={6} className={input} /></label><label><span className={label}>Eligibility</span><textarea value={form.eligibility || ''} onChange={(e) => set('eligibility', e.target.value)} rows={4} className={input} /></label><label><span className={label}>Required documents (one per line)</span><textarea value={form.required_documents.join('\n')} onChange={(e) => set('required_documents', lines(e.target.value))} rows={4} className={input} /></label></section>
      <section className="grid gap-4 border-t border-gray-700 pt-6 sm:grid-cols-2"><label><span className={label}>Source name *</span><input required value={form.source_name} onChange={(e) => set('source_name', e.target.value)} placeholder="Official institution notice" className={input} /></label><label><span className={label}>Original source URL *</span><input required type="url" value={form.source_url} onChange={(e) => set('source_url', e.target.value)} className={input} /></label><label><span className={label}>Verification</span><select value={form.verification_status} onChange={(e) => set('verification_status', e.target.value as Admission['verification_status'])} className={input}><option value="unverified">Unverified</option><option value="source_verified">Source verified</option><option value="institution_verified">Institution verified</option></select></label><label><span className={label}>Publishing status</span><select value={form.status} onChange={(e) => set('status', e.target.value as Admission['status'])} className={input}><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option><option value="archived">Archived</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_featured} onChange={(e) => set('is_featured', e.target.checked)} />Featured listing</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_sponsored} onChange={(e) => set('is_sponsored', e.target.checked)} />Sponsored placement</label>{form.is_sponsored && <label className="sm:col-span-2"><span className={label}>Visible sponsor label *</span><input required value={form.sponsor_label || ''} onChange={(e) => set('sponsor_label', e.target.value)} placeholder="Sponsored by Institution Name" className={input} /></label>}</section>
    </div><button disabled={saving} className="mt-6 flex items-center gap-2 rounded-lg bg-blue-600 px-6 py-3 text-sm font-bold text-white disabled:opacity-50"><Save className="h-4 w-4" />{saving ? 'Saving…' : admissionId ? 'Update admission' : 'Save admission'}</button>
  </form>
}
