import type { Metadata } from 'next'
import { BookOpen, CheckCircle2, Download, ExternalLink, FileQuestion } from 'lucide-react'
import { createServerSupabaseClient } from '@/lib/supabase'
import type { OldQuestion, Syllabus } from '@/types'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'Syllabus and Old Question Papers Nepal', description: 'Find verified university syllabi and past question papers by program, semester and year.' }
type Resource = (Syllabus & { kind: 'syllabus' }) | (OldQuestion & { kind: 'question' })
const checked = (value?: string | null) => value ? new Date(value).toLocaleDateString('en-NP', { month: 'short', year: 'numeric' }) : null

export default async function StudyResources({ searchParams }: { searchParams: { q?: string; type?: string; program?: string; university?: string } }) {
  const db = createServerSupabaseClient()
  const [syllabus, questions, programs, universities] = await Promise.all([
    db.from('syllabus').select('*,program:programs(name,slug),university:universities(name,short_name)').eq('is_published', true).order('created_at', { ascending: false }).limit(100),
    db.from('old_questions').select('*,program:programs(name,slug),university:universities(name,short_name)').eq('is_published', true).order('year', { ascending: false }).limit(100),
    db.from('programs').select('id,name').order('name'), db.from('universities').select('id,name,short_name').order('name'),
  ])
  let resources: Resource[] = [ ...((syllabus.data||[]).map(x=>({...x,kind:'syllabus' as const})) as Resource[]), ...((questions.data||[]).map(x=>({...x,kind:'question' as const})) as Resource[]) ]
  if (searchParams.type) resources = resources.filter(x=>x.kind===searchParams.type)
  if (searchParams.program) resources = resources.filter(x=>x.program_id===searchParams.program)
  if (searchParams.university) resources = resources.filter(x=>x.university_id===searchParams.university)
  if (searchParams.q) { const q=searchParams.q.toLowerCase(); resources=resources.filter(x=>`${x.kind==='syllabus'?x.title:x.subject} ${x.program?.name} ${x.university?.name}`.toLowerCase().includes(q)) }
  return <div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a302c]">Prepare with the right material</p><h1 className="mt-2 font-display text-4xl font-bold text-ink">Study resources</h1><p className="mt-3 leading-7 text-slate-600">Official syllabi and past question papers, organised by university, program, semester and year. Files are linked to their source—not anonymously uploaded.</p></div>
    <form className="mt-7 grid gap-3 rounded-xl border border-gray-200 bg-white p-4 md:grid-cols-4"><input name="q" defaultValue={searchParams.q} placeholder="Search subject or program" className="rounded-lg border border-gray-200 px-3 py-3 text-sm"/><select name="type" defaultValue={searchParams.type||''} className="rounded-lg border border-gray-200 bg-white px-3 text-sm"><option value="">Syllabus & questions</option><option value="syllabus">Syllabus only</option><option value="question">Past questions only</option></select><select name="program" defaultValue={searchParams.program||''} className="rounded-lg border border-gray-200 bg-white px-3 text-sm"><option value="">All programs</option>{(programs.data||[]).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><select name="university" defaultValue={searchParams.university||''} className="rounded-lg border border-gray-200 bg-white px-3 text-sm"><option value="">All universities</option>{(universities.data||[]).map(x=><option value={x.id} key={x.id}>{x.short_name||x.name}</option>)}</select><button className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-white md:col-span-4">Find resources</button></form>
    <div className="mt-8 flex items-center justify-between"><h2 className="text-xl font-bold text-ink">Available resources</h2><span className="text-sm text-slate-500">{resources.length} files</span></div>{resources.length?<div className="mt-4 grid gap-4 md:grid-cols-2">{resources.map(item=>{const title=item.kind==='syllabus'?item.title:item.subject;return <article key={`${item.kind}-${item.id}`} className="flex gap-4 rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${item.kind==='syllabus'?'bg-blue-50 text-blue-700':'bg-amber-50 text-amber-700'}`}>{item.kind==='syllabus'?<BookOpen className="h-5 w-5"/>:<FileQuestion className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{item.kind==='syllabus'?'Official syllabus':`Past question${item.kind==='question'&&item.year?` · ${item.year}`:''}`}</p><h3 className="mt-1 font-bold text-ink">{title}</h3><p className="mt-1 text-sm text-slate-500">{item.program?.name} · {item.university?.short_name||item.university?.name}{item.semester?` · ${item.semester}`:''}</p><div className="mt-4 flex flex-wrap items-center gap-3">{item.last_verified_at&&<span className="flex items-center gap-1 text-xs text-emerald-700"><CheckCircle2 className="h-3.5 w-3.5"/>Checked {checked(item.last_verified_at)}</span>}{item.source_url&&<a href={item.source_url} target="_blank" rel="noopener noreferrer" className="flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-primary"><ExternalLink className="h-3.5 w-3.5"/>Official source</a>}{item.file_url&&<a href={item.file_url} target="_blank" rel="noopener noreferrer" className="ml-auto flex items-center gap-1 text-sm font-bold text-primary"><Download className="h-4 w-4"/>Open file</a>}</div></div></article>})}</div>:<div className="mt-4 rounded-xl border border-gray-200 bg-white py-16 text-center text-sm text-gray-500">No verified resources match these filters yet.</div>}</div>
}
