'use client'

import { FormEvent, useEffect, useState } from 'react'
import { CalendarClock, Plus, Trash2 } from 'lucide-react'
import type { EntranceExam } from '@/types'

const empty = { title: '', exam_body: '', program: '', education_level: 'Bachelor', application_deadline: '', exam_date: '', fee: '', eligibility: '', source_name: '', source_url: '', syllabus_url: '', status: 'draft' }

export default function AdminEntranceExamsPage() {
  const [items, setItems] = useState<EntranceExam[]>([])
  const [form, setForm] = useState(empty)
  const [message, setMessage] = useState('')
  const [saving, setSaving] = useState(false)
  const load = () => fetch('/api/admin/entrance-exams', { cache: 'no-store' }).then(r => r.json()).then(data => setItems(Array.isArray(data) ? data : []))
  useEffect(() => { load() }, [])
  const field = 'rounded-lg border border-gray-700 bg-gray-900 px-3 py-2.5 text-sm text-white outline-none focus:border-blue-500'
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); const response = await fetch('/api/admin/entrance-exams', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); setSaving(false); if (!response.ok) return setMessage(data.error || 'Could not save exam'); setForm(empty); setMessage('Entrance exam saved.'); load() }
  async function changeStatus(id: string, status: string) { await fetch(`/api/admin/entrance-exams/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status }) }); load() }
  async function remove(id: string) { if (!window.confirm('Delete this entrance exam?')) return; await fetch(`/api/admin/entrance-exams/${id}`, { method: 'DELETE' }); load() }

  return <div className="p-8 text-gray-100"><div className="mb-6"><h1 className="flex items-center gap-2 text-2xl font-bold"><CalendarClock className="h-6 w-6 text-cyan-400"/>Entrance Exams</h1><p className="mt-1 text-sm text-gray-400">Publish only after checking the official notice.</p></div>
    <form onSubmit={submit} className="mb-8 grid gap-3 rounded-xl border border-gray-700 bg-gray-800 p-5 md:grid-cols-2"><input required placeholder="Exam title *" className={field} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><input placeholder="Exam body (e.g. MEC, IOE)" className={field} value={form.exam_body} onChange={e=>setForm({...form,exam_body:e.target.value})}/><input placeholder="Program or faculty" className={field} value={form.program} onChange={e=>setForm({...form,program:e.target.value})}/><select className={field} value={form.education_level} onChange={e=>setForm({...form,education_level:e.target.value})}><option>+2</option><option>Bachelor</option><option>Master</option><option>Diploma</option></select><label className="text-xs text-gray-400">Application deadline<input type="datetime-local" className={`mt-1 w-full ${field}`} value={form.application_deadline} onChange={e=>setForm({...form,application_deadline:e.target.value})}/></label><label className="text-xs text-gray-400">Exam date<input type="datetime-local" className={`mt-1 w-full ${field}`} value={form.exam_date} onChange={e=>setForm({...form,exam_date:e.target.value})}/></label><input type="number" min="0" placeholder="Application fee (NPR)" className={field} value={form.fee} onChange={e=>setForm({...form,fee:e.target.value})}/><input required placeholder="Official source name *" className={field} value={form.source_name} onChange={e=>setForm({...form,source_name:e.target.value})}/><input required type="url" placeholder="Official notice/source URL *" className={`${field} md:col-span-2`} value={form.source_url} onChange={e=>setForm({...form,source_url:e.target.value})}/><input type="url" placeholder="Syllabus URL (optional)" className={`${field} md:col-span-2`} value={form.syllabus_url} onChange={e=>setForm({...form,syllabus_url:e.target.value})}/><textarea placeholder="Eligibility summary" className={`${field} md:col-span-2`} value={form.eligibility} onChange={e=>setForm({...form,eligibility:e.target.value})}/><select className={field} value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">Save as draft</option><option value="published">Publish now</option></select><button disabled={saving} className="flex items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-bold disabled:opacity-60"><Plus className="h-4 w-4"/>{saving?'Saving…':'Add entrance exam'}</button>{message&&<p className="md:col-span-2 text-sm text-amber-300">{message}</p>}</form>
    <div className="overflow-hidden rounded-xl border border-gray-700 bg-gray-800"><div className="border-b border-gray-700 px-5 py-4 font-bold">{items.length} records</div>{items.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 border-b border-gray-700/60 px-5 py-4 last:border-0"><div><p className="font-semibold text-white">{item.title}</p><p className="mt-1 text-xs text-gray-400">{item.exam_body||'No exam body'} · {item.application_deadline?new Date(item.application_deadline).toLocaleDateString():'Deadline not announced'}</p></div><div className="flex items-center gap-2"><select value={item.status} onChange={e=>changeStatus(item.id,e.target.value)} className="rounded border border-gray-600 bg-gray-900 px-2 py-1.5 text-xs"><option value="draft">Draft</option><option value="published">Published</option><option value="closed">Closed</option></select><button onClick={()=>remove(item.id)} className="rounded p-2 text-gray-400 hover:bg-gray-700 hover:text-red-400"><Trash2 className="h-4 w-4"/></button></div></div>)}{!items.length&&<p className="py-12 text-center text-sm text-gray-500">No entrance exams added yet.</p>}</div>
  </div>
}
